name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Buildozer and Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip git autoconf autotools-dev automake libtool libtool-bin libltdl-dev pkg-config zlib1g-dev libncurses-dev libssl-dev cmake libffi-dev
          python3 -m pip install --upgrade pip --break-system-packages
          python3 -m pip install Cython==0.29.33 buildozer==1.5.0 python-for-android==2024.1.21 --break-system-packages

      - name: Build APK
        env:
          BUILDOZER_ACCEPT_ANDROID_SDK_LICENSE: "1"
          BUILDOZER_WARN_ON_ROOT: "0"
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-Package
          path: bin/*.apk
